"""Operator Agent - executes the remediation plan via Lambda/SSM/Terraform and validates the outcome."""

from agents.common.agent.base_agent import AgentBase
from agents.operator_agent.tools import execute_resolution, update_incident_memory, validate_resolution


class OperatorAgent(AgentBase):

    @property
    def name(self) -> str:
        return "operator_agent"

    @property
    def description(self) -> str:
        return "Executes remediation plans generated by the Error Classifier Agent."

    def invoke(self, state: dict) -> dict:
        state["execution_result"] = execute_resolution(state.get("remediation_plan", {}))
        state["resolved"] = validate_resolution(state)

        update_incident_memory(
            {
                "incident_id": state.get("incident_id"),
                "error_type": state.get("error_type"),
                "error_message": state.get("error_message"),
                "root_cause": state.get("root_cause"),
                "remediation_plan": state.get("remediation_plan"),
                "status": "RESOLVED" if state["resolved"] else "FAILED",
            }
        )
        return state
