import os
import sys
import json

from dataclasses import dataclass
from typing import Any

from langgraph.graph import StateGraph, END
from langgraph.types import RetryPolicy

from core.agent.Agent import AgentBase
from core.util.ConfigLoader import (load_env_variables,get_secret)
from core.model_provider.factory import (ModelFactory)
from a2a.types import AgentSkill
from tools import (execute_resolution, validate_resolution, route_resolution)

@dataclass
class OperatorState:
    messages: list[Any]
    metadata: dict[str, Any]
    execution_result: dict = None
    validation_result: bool = False

class OperatorAgent(AgentBase[OperatorState]):
    @property
    def name(self):
        return "Operator_Agent"

    @property
    def description(self):
        return "Executes remediation plans generated by Knowledge Base Agent."

    def __init__(self):
        self.env = load_env_variables()
        secret_name = self.env["SECRET_NAME"]
        self.model_api_key = get_secret(secret_name)

        self.llm = (
            ModelFactory
            .create_provider(
                provider=self.env["PROVIDER"],
                model_name=self.env["MODEL"],
                api_key=self.model_api_key
            )
            .get_llm()
        )

        skill = AgentSkill(
            id="operator_agent",
            name="Operator Agent",
            description="Executes remediation plans",
            tags=["operator","self-healing","aws","databricks"]
        )
        self.initialize_graph()
        super().__init__(llm=self.llm, agent_skill=skill)

    def execute_resolution_node(self,state: OperatorState):
        plan = state.metadata["resolution_plan"]
        result = execute_resolution(plan)
        state.execution_result = result
        state.metadata["execution_result"] = result
        return state

    def validate_resolution_node(self,state: OperatorState):
        plan= state.metadata["resolution_plan"]
        result = validate_resolution(plan)
        state.validation_result = result
        state.metadata["execution_result"] = result
        return state

    def resolution_router(self,state: OperatorState):
        result = route_resolution(state.validation_result)
        return result.lower()

    #memory node
    def update_memory_node(self,state):
        update_incident_memory(
            {
                "incident_id":
                state.metadata[
                    "incident_id"
                ],
                "status":
                "SUCCESS",
                "resolution_plan":
                state.metadata["resolution_plan"]
            }
        )
        return state
    
    def success_node(self, state: OperatorState):    
            state.metadata["final_status"] = "SUCCESS"    
            return state
    
    def failure_node(self,state):
        state.metadata["final_status"] = "FAILED"
        return state

    async def stream(self, query, thread_id,metadata=None):
        state = OperatorState(
        messages=[("user", query)],
        metadata=metadata)
        return {
            "status":
            state.metadata["final_status"]
        }

    def _build_graph(self):
        builder = StateGraph(OperatorState)
        builder.add_node(
            "execute_resolution",
            self.execute_resolution_node,
            retry=RetryPolicy(max_attempts=3)
        )
        builder.add_node(
            "validate_resolution",
            self.validate_resolution_node
        )
        builder.add_node(
            "update_memory",
            self.update_memory_node
        )
        builder.add_node(
             "success",
              self.success_node
        )
        builder.add_node(
            "failure",
            self.failure_node
        )
        builder.set_entry_point(
            "execute_resolution"
        )
        builder.add_edge(
            "execute_resolution",
            "validate_resolution"
        )
        builder.add_conditional_edges(
            "validate_resolution",
            self.resolution_router,
            {
                "resolved":"update_memory",
                "success": "success",
                "failed": "failure"
            }
        )
        builder.add_edge(
            "update_memory",
             "success",
            END
        )
        builder.add_edge(
            "failure",
            END
        )
        return builder.compile()

if __name__ == "__main__":
    agent = OperatorAgent()
    base_url = os.getenv("AGENT_BASE_URL")
    agent_port = os.getenv("AGENT_BASE_PORT")
    agent.run_server(host="0.0.0.0", port=8000, host_base_url=f'http://{base_url}:{agent_port}', path="/v2/agents/operator_agent")
